### PR TITLE
Quality of life improvements

### PR DESCRIPTION
**Pull request by jrbudda**
- Add gamedata\kerbalvr\win32 + win64 to dll search path, allows normal
KSP mod install entirely in gamedata.
- Auto set texture type
- Only works with -force-d3d11, and even then likes to lock up/crash.
- Init SteamVR on game launch, seems to help the crashing a little.

### CODE REVIEW

**Comment by Vivero** [comment]
Regarding the texture format thing, good find. That explains the incompatibilities. The DLL search path is wonderful, didn't know that was possible. I think the changes are fine, I'll go ahead and merge them.

**Comment by jrbudda** [comment]
sadly i've been looking into this more.. I don't know how possible getting this to work on d3d11 is going to be. All the docs say the calls to waitgetposes and .submit need to be on the rendering thread, and there's just no accessing it in a monobehavior plugin that I can see. Unity has openvr support built into it now, but I've pretty sure it has to be enabled in the application at build time to be usable.

**Comment by Vivero** [comment]
Dang, that sucks. Yep, I've seen that option for "Virtual Reality Supported" in the project settings for a Unity app. I remember one time seeing an error log message about that particular project setting not being enabled, so I'm pretty certain Squad has it disabled for KSP.

**Comment by jrbudda** [comment]
I tried syncing the openvr calls to the render thread by calling waitforendofframe, but that still crashed. Also tried using the camera events to set the projection matricies and let the normal game render happen then submit on the camera. onrender.event... still crashes. It's just very unhappy in general. Maybe Valve will add support for whatever weird texture format the Unity 5.4 'opengl' is using. Really really not sure why that should have broken anything in the first place, opengl generally backwards compatible.

**Pull request merged**
