### PR TITLE
lazy init openvr

### PR DESCRIPTION
**Pull request by jrbudda**
start steamvr on demand, not with game load, might not want to play in vr :)

### CODE REVIEW

**Comment by Vivero** [comment]
Yea probably a good feature :)
I'll roll it in soon. Lately it's been a little difficult finding time to dedicate to KerbalVR.

**Comment by jrbudda** [comment]
So whats the current deal with the Glove thing? I'd like to work on the version-3 branch cause it's farther ahead but it doesn't run as-is, no glove pre-fab?

**Comment by Vivero** [comment]
Yea my bad, I was fussing around with some prefab model assets until finally got something working. I pushed a bunch of stuff, the `version-3` branch should be back in a working state now. Which means now I can merge your stuff soon.

**Comment by jrbudda** [comment]
Dude saw your post on reddit, looks AWESOME.

**Comment by Vivero** [comment]
hmm something's not quite right. to get this to work, I have to press Enable VR (then it freezes for a hot second while OpenVR inits), but nothing is displayed on the headset. Then I press Disable, then Enable again, and all works fine now. haven't had a chance to dig into what's going on

**Comment by jrbudda** [comment]
OK, i couldn't actually test it cause of the glove thing. I just wanted steamvr not to launch every time without having to uninstall the mod :)

I will update to the latest and take a look at it. Anything else in particular you think needs working on?

**Pull request merged**
