### PR TITLE
Click on all the things

### PR DESCRIPTION
**Pull request by jrbudda**

### CODE REVIEW

**Comment by jrbudda** [comment]
ya ezpz.

**Comment by Vivero** [comment]
Click on... _all_ the things?!?

Dude this is really great, I'll check it out when I get home in a few hours. Can't wait!

**Comment by Vivero** [comment]
omg so `obj.SendMessage("OnMouseDown");` actually works? I was clearly doing something wrong with it then  -_-

**Comment by jrbudda** [comment]
Like you said sometimes it just takes a fresh pair of eyes. I sit pretty much allll day and night in the Vivecraft discord server if you wanna come and chat live about any of this. Been on a kerbal kick lately.

**Pull request merged**
